## Detecting-patterns-in-purchase-history-using-association-rule-learning-methods

### 1. Experimental Dataset as proof of concept

In [16]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.expand_frame_repr', False)

In [17]:
data_simple_input =[\
["I_0", "I_1", "I_2", "I_3", "I_4", "I_5", "I_7"],
["I_0", "I_2", "I_3", "I_4", "I_5", "I_6", "I_7"],
["I_0", "I_2", "I_3", "I_8"],
["I_0", "I_1", "I_4", "I_6", "I_7", "I_8", "I_9"],
["I_0", "I_1", "I_4", "I_8", "I_9"],
["I_0", "I_1", "I_7", "I_8", "I_9"],
["I_0", "I_5", "I_8"],
["I_0", "I_1", "I_3", "I_9"],
["I_1", "I_2", "I_8"],
["I_1", "I_4", "I_9"]]

# Counts:
# I_0:8
# I_1:7
# I_8:6
# I_4:5
# I_9:5
# I_2:4
# I_3:4
# I_7:4
# I_5:3
# I_6:2

### 1. Traditional alorthms from libraries

#### 1.1 Apriori
APriori is the first tradtional ruiles algorithm.

In [18]:
# Imports
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import fpgrowth

In [19]:
te = TransactionEncoder()
te_ary = te.fit(data_simple_input).transform(data_simple_input)
T = pd.DataFrame(te_ary, columns=te.columns_)
T

     I_0    I_1    I_2    I_3    I_4    I_5    I_6    I_7    I_8    I_9
0   True   True   True   True   True   True  False   True  False  False
1   True  False   True   True   True   True   True   True  False  False
2   True  False   True   True  False  False  False  False   True  False
3   True   True  False  False   True  False   True   True   True   True
4   True   True  False  False   True  False  False  False   True   True
5   True   True  False  False  False  False  False   True   True   True
6   True  False  False  False  False   True  False  False   True  False
7   True   True  False   True  False  False  False  False  False   True
8  False   True   True  False  False  False  False  False   True  False
9  False   True  False  False   True  False  False  False  False   True

In [20]:
from mlxtend.frequent_patterns import apriori, association_rules

frequent_itemsets = apriori(T, min_support=0.1,use_colnames=True)
frequent_itemsets

     support                             itemsets
0        0.8                                (I_0)
1        0.7                                (I_1)
2        0.4                                (I_2)
3        0.4                                (I_3)
4        0.5                                (I_4)
..       ...                                  ...
303      0.1       (I_1, I_7, I_4, I_9, I_6, I_8)
304      0.1       (I_7, I_5, I_4, I_2, I_6, I_3)
305      0.1  (I_1, I_7, I_0, I_4, I_5, I_2, I_3)
306      0.1  (I_1, I_7, I_0, I_4, I_9, I_6, I_8)
307      0.1  (I_7, I_0, I_4, I_5, I_2, I_6, I_3)

[308 rows x 2 columns]

In [21]:
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.1)
rules

     antecedents                     consequents  antecedent support  consequent support  support  confidence      lift  leverage  conviction
0          (I_0)                           (I_1)                 0.8                 0.7      0.5    0.625000  0.892857     -0.06       0.800
1          (I_1)                           (I_0)                 0.7                 0.8      0.5    0.714286  0.892857     -0.06       0.700
2          (I_0)                           (I_2)                 0.8                 0.4      0.3    0.375000  0.937500     -0.02       0.960
3          (I_2)                           (I_0)                 0.4                 0.8      0.3    0.750000  0.937500     -0.02       0.800
4          (I_0)                           (I_3)                 0.8                 0.4      0.4    0.500000  1.250000      0.08       1.200
...          ...                             ...                 ...                 ...      ...         ...       ...       ...         ...
5179       (I_4)  (I_7, I_0, I_5, I_2, I_6, I_3)                 0.5                 0.1      0.1    0.200000  2.000000      0.05       1.125
5180       (I_5)  (I_7, I_0, I_4, I_2, I_6, I_3)                 0.3                 0.1      0.1    0.333333  3.333333      0.07       1.350
5181       (I_2)  (I_7, I_0, I_4, I_5, I_6, I_3)                 0.4                 0.1      0.1    0.250000  2.500000      0.06       1.200
5182       (I_6)  (I_7, I_0, I_4, I_5, I_2, I_3)                 0.2                 0.2      0.1    0.500000  2.500000      0.06       1.600
5183       (I_3)  (I_7, I_0, I_4, I_5, I_2, I_6)                 0.4                 0.1      0.1    0.250000  2.500000      0.06       1.200

[5184 rows x 9 columns]

#### 1.2 FP-Growth
FP-Growth gives exactly the same output, but is much more efficient, especially when using big data.

In [22]:
from mlxtend.frequent_patterns import fpgrowth

fpgrowth(T, min_support=0.5,use_colnames=True)

   support    itemsets
0      0.8       (I_0)
1      0.7       (I_1)
2      0.5       (I_4)
3      0.6       (I_8)
4      0.5       (I_9)
5      0.5  (I_0, I_1)
6      0.5  (I_0, I_8)
7      0.5  (I_9, I_1)

#### 2. Modified implementation of FP-Growth as Basis

#### 2.1 Classical implementation for proving correct algorithm

The modified implementation of FP-Growth will give back the same result as the classical algorithms.
This means, without any date & profit parameter for weighted support, basically thrmalgorithm works as expected.
One fundamental modification has been done, when finding the antecedent leading to the the combined new antecedent & consequent.
The modification only considers "one antecedent", instead of many. The "one antecedent" is taken from the strict tree-structure (path) from high support to low support.
##### Advantages:
- Clearer rules & No duplication of changing antecedent leading to the  same itemset
- Much better performance, especially for big data. All figures can be derived from one Loop through all transactions O(n)-complexity for whole dataset. Inside the paths there is O(n*2) complexity, but the paths are usually very small compared to the whole dataset. Alternatively all combinations of paths have to be looped again
##### Disadvantages:
- Potential loss of information, if onbe rule for a very special antecedent leading to the itemset was decisive

In [23]:
T = pd.read_csv("datasets/proof_of_concept/transactions.csv")
T = T.groupby("transaction",dropna=True)["item"].agg([lambda x: list(x),"count"])
T

                                      <lambda_0>  count
transaction
T_01         [I_0, I_1, I_2, I_3, I_4, I_5, I_7]      7
T_02         [I_0, I_2, I_3, I_4, I_5, I_6, I_7]      7
T_03                        [I_0, I_2, I_3, I_8]      4
T_04         [I_0, I_1, I_4, I_6, I_7, I_8, I_9]      7
T_05                   [I_0, I_1, I_4, I_8, I_9]      5
T_06                   [I_0, I_1, I_7, I_8, I_9]      5
T_07                             [I_0, I_5, I_8]      3
T_08                        [I_0, I_1, I_3, I_9]      4
T_09                   [I_1, I_2, I_8, I_8, I_8]      5
T_10                             [I_1, I_4, I_9]      3

In [24]:
import modified_fp_growth_algorithm.modified_fp_growth_latest as mod_fp_growth

rules = mod_fp_growth.fpgrowthFromDataFrame(T, minSupRatio=0.1, maxSupRatio=1, minConf=0.1, item_col=1) #Traditional Association Rules
rules

                         antecedent sup_antecedent consequent  sup_consequent                antecedent&consequent  sup_ant&cons  sup_perc_ant&cons confidence      lift improvement
0                                []             NA      [I_0]               8                                [I_0]             8                0.8         NA        NA          NA
1                                []             NA      [I_1]               7                                [I_1]             7                0.7         NA        NA          NA
2                                []             NA      [I_8]               6                                [I_8]             6                0.6         NA        NA          NA
3                             [I_0]              8      [I_1]               7                           [I_0, I_1]             5                0.5      0.625  0.892857      -0.075
4                                []             NA      [I_9]               5                                [I_9]             5                0.5         NA        NA          NA
..                              ...            ...        ...             ...                                  ...           ...                ...        ...       ...         ...
303       [I_1, I_7, I_0, I_2, I_3]              1      [I_5]               3       [I_1, I_7, I_0, I_5, I_2, I_3]             1                0.1        1.0  3.333333         0.7
304                 [I_0, I_4, I_3]              2      [I_6]               2                 [I_0, I_4, I_3, I_6]             1                0.1        0.5       2.5         0.3
305       [I_1, I_7, I_4, I_2, I_3]              1      [I_5]               3       [I_1, I_7, I_5, I_4, I_2, I_3]             1                0.1        1.0  3.333333         0.7
306  [I_1, I_7, I_0, I_4, I_2, I_3]              1      [I_5]               3  [I_1, I_7, I_0, I_4, I_5, I_2, I_3]             1                0.1        1.0  3.333333         0.7
307                 [I_7, I_4, I_1]              2      [I_5]               3                 [I_7, I_5, I_4, I_1]             1                0.1        0.5  1.666667         0.2

[308 rows x 10 columns]

#### 2.2 Weighted support with date-decay function

The idea of a date support decay function is, that recent transactions should have normally more weight, than older ones.
There are used the following paramters:
x will be determined between [0,1]
- max_date=datetime.datetime(2022, 11, 10),
-> This is the max date, x of max_date is 1
- date_range=10,
-> This is the range of x, max_date - range = 0
- date_sensitivity = lambda x: 1 / (1 + math.exp(-10*x+5))
-> This is the function used for date exemplatory. It is a modfied sigmoid, using the curve range [0,1] to represent date decay
-> This has still to be calibrated and could differ for every new Dataset. For example the curve could be rather flat around 1 for only a small effect
-> In the example with lambda x: 1 / (1 + math.exp(-10*x+5)), the curve is quite extreme and maybe overvalues recent events

In [25]:
T = pd.read_csv("datasets/proof_of_concept/transactions.csv")
T["date"] = pd.to_datetime(T["date"],format='%Y-%m-%d')
T = T.groupby("transaction",dropna=True)["item","date"].agg([lambda x: list(x)])
T

C:\Users\david\AppData\Local\Temp/ipykernel_15152/658750622.py:3: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  T = T.groupby("transaction",dropna=True)["item","date"].agg([lambda x: list(x)])

                                            item                                               date
                                        <lambda>                                           <lambda>
transaction
T_01         [I_0, I_1, I_2, I_3, I_4, I_5, I_7]  [2022-11-01 00:00:00, 2022-11-01 00:00:00, 202...
T_02         [I_0, I_2, I_3, I_4, I_5, I_6, I_7]  [2022-11-02 00:00:00, 2022-11-02 00:00:00, 202...
T_03                        [I_0, I_2, I_3, I_8]  [2022-11-02 00:00:00, 2022-11-03 00:00:00, 202...
T_04         [I_0, I_1, I_4, I_6, I_7, I_8, I_9]  [2022-11-04 00:00:00, 2022-11-04 00:00:00, 202...
T_05                   [I_0, I_1, I_4, I_8, I_9]  [2022-11-05 00:00:00, 2022-11-05 00:00:00, 202...
T_06                   [I_0, I_1, I_7, I_8, I_9]  [2022-11-06 00:00:00, 2022-11-06 00:00:00, 202...
T_07                             [I_0, I_5, I_8]  [2022-11-07 00:00:00, 2022-11-07 00:00:00, 202...
T_08                        [I_0, I_1, I_3, I_9]  [2022-11-08 00:00:00, 2022-11-08 00:00:00, 202...
T_09                   [I_1, I_2, I_8, I_8, I_8]  [2022-11-09 00:00:00, 2022-11-09 00:00:00, 202...
T_10                             [I_1, I_4, I_9]  [2022-11-10 00:00:00, 2022-11-10 00:00:00, 202...

In [26]:
import math
import datetime

rules = mod_fp_growth.fpgrowthFromDataFrame(\
    T,
    minSupRatio=0.5,
    maxSupRatio=1,
    minConf=0,
    item_col=1,
    date_col=2,
    max_date=datetime.datetime(2022, 11, 10),
    date_range=10,
    date_sensitivity = lambda x: 1 / (1 + math.exp(-10*x+5))
    ) #Only Date

rules

  antecedent sup_antecedent consequent  sup_consequent antecedent&consequent  sup_ant&cons  sup_perc_ant&cons confidence     lift improvement
0         []             NA      [I_1]        4.445881                 [I_1]      4.445881           0.820042         NA       NA          NA
1         []             NA      [I_8]        3.482014                 [I_8]      3.482014           0.642257         NA       NA          NA
2         []             NA      [I_0]        3.446209                 [I_0]      3.446209           0.635652         NA       NA          NA
3         []             NA      [I_9]        3.445881                 [I_9]      3.445881           0.635592         NA       NA          NA
4      [I_1]       4.445881      [I_9]        3.445881            [I_9, I_1]      3.445881           0.635592   0.775073  1.21945    0.139481

#### 2.3 Weighted support with profit-dependent function

The main driver for business it not the frequency of items, but the proftibility. One can normally assume, that more frequent items are lower in price, higher in margin, but can be equal with not frequent but highly priced articles.
I've reas in one article, one reason association rules are not applied that often is the lack of relevance. Frequency is only one part, but not the ultimate driver for business.
Instead of just counting each transaction, we weight each article of every transation and set it in a relationship with association rules.
The result has to be interpreted carefully. It cannot be interpreted the same as the traditional methods. The sup_ant&cons is just the profit resulting from a relation. The % of sup_ant&cons represents the percentage of the whole profit of sum of all articles.

The interference of profit and frequency could be solved post association rules creation by business when later connecting all frequencies with profit from articles. However, there we have the problem, that we sorted out the least frequent articles already because of performance or releance and lose crucial relations. Moreover this approach would be not that straightforward.

In [27]:
T = pd.read_csv("datasets/proof_of_concept/transactions.csv")
T = T.groupby("transaction",dropna=True)["item","profit"].agg([lambda x: list(x)])
T

C:\Users\david\AppData\Local\Temp/ipykernel_15152/1620300645.py:2: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  T = T.groupby("transaction",dropna=True)["item","profit"].agg([lambda x: list(x)])

                                            item                         profit
                                        <lambda>                       <lambda>
transaction
T_01         [I_0, I_1, I_2, I_3, I_4, I_5, I_7]   [10, 20, 30, 40, 50, 60, 80]
T_02         [I_0, I_2, I_3, I_4, I_5, I_6, I_7]   [10, 30, 40, 50, 60, 70, 80]
T_03                        [I_0, I_2, I_3, I_8]               [10, 30, 40, 90]
T_04         [I_0, I_1, I_4, I_6, I_7, I_8, I_9]  [10, 20, 50, 70, 80, 90, 100]
T_05                   [I_0, I_1, I_4, I_8, I_9]          [10, 20, 50, 90, 100]
T_06                   [I_0, I_1, I_7, I_8, I_9]          [10, 20, 80, 90, 100]
T_07                             [I_0, I_5, I_8]                   [10, 60, 90]
T_08                        [I_0, I_1, I_3, I_9]              [10, 20, 40, 100]
T_09                   [I_1, I_2, I_8, I_8, I_8]           [20, 30, 90, 90, 90]
T_10                             [I_1, I_4, I_9]                  [20, 50, 100]

In [28]:
import math
import datetime

rules = mod_fp_growth.fpgrowthFromDataFrame(\
    T,
    minSupRatio=0.1,
    maxSupRatio=1,
    minConf=0,
    item_col=1,
    profit_col=2,
    max_profit = 100,
    profit_sensitivity = lambda x : 1 * x
    ) #Only Profit
rules

   antecedent sup_antecedent consequent  sup_consequent antecedent&consequent  sup_ant&cons  sup_perc_ant&cons confidence      lift improvement  profit_associated  perc_of_total_profit  profit_associated_prev  net_change  profit_last_item  loss_by_change
0          []             NA      [I_8]               6                 [I_8]             6                0.6         NA        NA          NA              720.0              0.275862                     0.0         0.0             720.0             0.0
1       [I_8]              6      [I_9]               5            [I_8, I_9]             3                0.3        0.5       1.0         0.0              660.0              0.252874                   720.0       -60.0             300.0          -360.0
2  [I_8, I_9]              3      [I_7]               4       [I_7, I_8, I_9]             2                0.2   0.666667  1.666667    0.266667              600.0              0.229885                   660.0       -60.0             160.0          -220.0
3          []             NA      [I_9]               5                 [I_9]             5                0.5         NA        NA          NA              500.0              0.191571                     0.0         0.0             500.0             0.0
4       [I_8]              6      [I_7]               4            [I_7, I_8]             2                0.2   0.333333  0.833333   -0.066667              400.0              0.153257                   720.0      -320.0             160.0          -480.0
5       [I_9]              5      [I_7]               4            [I_7, I_9]             2                0.2        0.4       1.0         0.0              360.0              0.137931                   500.0      -140.0             160.0          -300.0
6          []             NA      [I_7]               4                 [I_7]             4                0.4         NA        NA          NA              320.0              0.122605                     0.0         0.0             320.0             0.0

#### 2.4 Combined weighted suppport of date-decay and profit dependent function

Now as a last step we combine the date decay function with the the profit measure view.
It will consider both.

In [29]:
T = pd.read_csv("datasets/proof_of_concept/transactions.csv")
T["date"] = pd.to_datetime(T["date"],format='%Y-%m-%d')
T = T.groupby("transaction",dropna=True)["item","date","profit"].agg([lambda x: list(x)])
T

C:\Users\david\AppData\Local\Temp/ipykernel_15152/815056449.py:3: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  T = T.groupby("transaction",dropna=True)["item","date","profit"].agg([lambda x: list(x)])

                                            item                                               date                         profit
                                        <lambda>                                           <lambda>                       <lambda>
transaction
T_01         [I_0, I_1, I_2, I_3, I_4, I_5, I_7]  [2022-11-01 00:00:00, 2022-11-01 00:00:00, 202...   [10, 20, 30, 40, 50, 60, 80]
T_02         [I_0, I_2, I_3, I_4, I_5, I_6, I_7]  [2022-11-02 00:00:00, 2022-11-02 00:00:00, 202...   [10, 30, 40, 50, 60, 70, 80]
T_03                        [I_0, I_2, I_3, I_8]  [2022-11-02 00:00:00, 2022-11-03 00:00:00, 202...               [10, 30, 40, 90]
T_04         [I_0, I_1, I_4, I_6, I_7, I_8, I_9]  [2022-11-04 00:00:00, 2022-11-04 00:00:00, 202...  [10, 20, 50, 70, 80, 90, 100]
T_05                   [I_0, I_1, I_4, I_8, I_9]  [2022-11-05 00:00:00, 2022-11-05 00:00:00, 202...          [10, 20, 50, 90, 100]
T_06                   [I_0, I_1, I_7, I_8, I_9]  [2022-11-06 00:00:00, 2022-11-06 00:00:00, 202...          [10, 20, 80, 90, 100]
T_07                             [I_0, I_5, I_8]  [2022-11-07 00:00:00, 2022-11-07 00:00:00, 202...                   [10, 60, 90]
T_08                        [I_0, I_1, I_3, I_9]  [2022-11-08 00:00:00, 2022-11-08 00:00:00, 202...              [10, 20, 40, 100]
T_09                   [I_1, I_2, I_8, I_8, I_8]  [2022-11-09 00:00:00, 2022-11-09 00:00:00, 202...           [20, 30, 90, 90, 90]
T_10                             [I_1, I_4, I_9]  [2022-11-10 00:00:00, 2022-11-10 00:00:00, 202...                  [20, 50, 100]

In [30]:
import math
import datetime

rules = mod_fp_growth.fpgrowthFromDataFrame(
    T,
    # General parameters
    minSupRatio=0.1,
    maxSupRatio=1,
    minConf=0,
    item_col=1,
    # Date parameters
    date_col=2,
    max_date=datetime.datetime(2022, 11, 10),
    date_range=10,
    date_sensitivity = lambda x: 1 / (1 + math.exp(-10*x+5)),
    # Profit parameters
    profit_col=3,
    max_profit = 10,
    profit_sensitivity = lambda x : 1 * x
    )

rules.to_excel("fp_groth_out.xlsx",index=False)
rules

   antecedent sup_antecedent consequent  sup_consequent antecedent&consequent  sup_ant&cons  sup_perc_ant&cons confidence      lift improvement  profit_associated  perc_of_total_profit  profit_associated_prev  net_change  profit_last_item  loss_by_change
0          []             NA      [I_8]        3.482014                 [I_8]      3.482014           0.642257         NA        NA          NA         417.841655              0.361120                0.000000    0.000000        417.841655        0.000000
1          []             NA      [I_9]        3.445881                 [I_9]      3.445881           0.635592         NA        NA          NA         344.588128              0.297811                0.000000    0.000000        344.588128        0.000000
2       [I_8]       3.482014      [I_9]        3.445881            [I_8, I_9]      1.500000           0.276675   0.430785   0.67777   -0.204807         330.000000              0.285203              417.841655  -87.841655        150.000000     -237.841655
3  [I_8, I_9]            1.5      [I_7]        1.065412       [I_7, I_8, I_9]      1.000000           0.184450   0.666667  3.392446    0.470152         300.000000              0.259276              330.000000  -30.000000         80.000000     -110.000000

#### 3. Analysis of Kaggle Dataset

#### 3.1 Investigating Dataset

#### 3.1 Description
Kaggle Dataset: https://www.kaggle.com/datasets/mkechinov/ecommerce-purchase-history-from-electronics-store <br>
The Dataset is Open-Source <br>
This Dataset contains purchase data from April 2020 to November 2020 from a large home appliances and electronics online store. <br>
Each row in the file represents an event. All events are related to products and users. Each event is like many-to-many relation between products and users. <br>

In [31]:
import os

'c:\\Users\\david\\Desktop\\MASTER_THESIS\\Detecting-patterns-in-purchase-history-using-association-rule-learning-methods'

In [32]:
import glob
import os

# setting the path for joining multiple files
files = os.path.join(os.getcwd(), "Datasets/ecommerce_purchase_history_from_electronic_store/dataset*.csv")

# list of merged files returned
files = glob.glob(files)

# joining files with concat and read_csv
data_raw = pd.concat(map(pd.read_csv, files), ignore_index=True)

data_raw

                      event_time             order_id           product_id   category_id                category_code     brand   price       user_id
0        2020-04-24 11:50:39 UTC  2294359932054536986  1515966223509089906  2.268105e+18           electronics.tablet   samsung  162.01  1.515916e+18
1        2020-04-24 11:50:39 UTC  2294359932054536986  1515966223509089906  2.268105e+18           electronics.tablet   samsung  162.01  1.515916e+18
2        2020-04-24 14:37:43 UTC  2294444024058086220  2273948319057183658  2.268105e+18  electronics.audio.headphone    huawei   77.52  1.515916e+18
3        2020-04-24 14:37:43 UTC  2294444024058086220  2273948319057183658  2.268105e+18  electronics.audio.headphone    huawei   77.52  1.515916e+18
4        2020-04-24 19:16:21 UTC  2294584263154074236  2273948316817424439  2.268105e+18                          NaN   karcher  217.57  1.515916e+18
...                          ...                  ...                  ...           ...                          ...       ...     ...           ...
2633516  2020-11-21 10:10:01 UTC  2388440981134693942  1515966223526602848  2.268105e+18       electronics.smartphone      oppo  138.87  1.515916e+18
2633517  2020-11-21 10:10:13 UTC  2388440981134693943  1515966223509089282  2.268105e+18       electronics.smartphone     apple  418.96  1.515916e+18
2633518  2020-11-21 10:10:30 UTC  2388440981134693944  1515966223509089917  2.268105e+18   appliances.personal.scales     vitek   12.48  1.515916e+18
2633519  2020-11-21 10:10:30 UTC  2388440981134693944  2273948184839454837  2.268105e+18                          NaN  moulinex   41.64  1.515916e+18
2633520  2020-11-21 10:10:30 UTC  2388440981134693944  1515966223509127566  2.268105e+18   appliances.kitchen.blender   redmond   53.22  1.515916e+18

[2633521 rows x 8 columns]

In [33]:
unique_items = data_raw[["product_id","category_id","category_code","brand","price"]].drop_duplicates(subset = "product_id").astype("str")


unique_items

                  product_id             category_id                     category_code    brand    price
0        1515966223509089906   2.268105426648171e+18                electronics.tablet  samsung   162.01
2        2273948319057183658  2.2681054301629978e+18       electronics.audio.headphone   huawei    77.52
4        2273948316817424439    2.26810547136784e+18                               nan  karcher   217.57
5        1515966223509261697   2.268105442636858e+18           furniture.kitchen.table  maestro    39.33
6        1515966223509104892   2.268105428166509e+18            electronics.smartphone    apple  1387.01
...                      ...                     ...                               ...      ...      ...
2633417  2388434452476091001  2.2681053894446948e+18           appliances.kitchen.hood  indesit   245.35
2633434  2388434452476152446  2.2681054280742344e+18             electronics.telephone     inoi    25.44
2633435  2388434452476709970   2.268105462249423e+18                     sport.bicycle     zevs    92.34
2633455  2388434452476864505   2.268105428166509e+18            electronics.smartphone    apple  1574.05
2633461  2388434452475958605   2.268105393848714e+18  appliances.kitchen.refrigerators  samsung   879.61

[25113 rows x 5 columns]

In [34]:
data_raw["date"] = pd.to_datetime(data_raw['event_time']).dt.date
max_date = data_raw["date"].max()
data_raw["margin"] = 0.1
data_raw["profit"] = data_raw["price"] * data_raw["margin"]
max_profit = data_raw["profit"].max()

data = data_raw.groupby("order_id",dropna=True)["product_id","date","price","margin"].agg(lambda x: list(x))

data

C:\Users\david\AppData\Local\Temp/ipykernel_15152/16707732.py:7: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  data = data_raw.groupby("order_id",dropna=True)["product_id","date","price","margin"].agg(lambda x: list(x))

                                                            product_id                                              date                                 price                margin
order_id
2294359932054536986         [1515966223509089906, 1515966223509089906]                          [2020-04-24, 2020-04-24]                      [162.01, 162.01]            [0.1, 0.1]
2294444024058086220         [2273948319057183658, 2273948319057183658]                          [2020-04-24, 2020-04-24]                        [77.52, 77.52]            [0.1, 0.1]
2294584263154074236                              [2273948316817424439]                                      [2020-04-24]                              [217.57]                 [0.1]
2295716521449619559                              [1515966223509261697]                                      [2020-04-26]                               [39.33]                 [0.1]
2295740594749702229  [1515966223509104892, 1515966223509104892, 151...  [2020-04-26, 2020-04-26, 2020-04-26, 2020-04-26]  [1387.01, 1387.01, 1387.01, 1387.01]  [0.1, 0.1, 0.1, 0.1]
...                                                                ...                                               ...                                   ...                   ...
2388440981134693940                              [2273948246856434093]                                      [2020-11-21]                               [16.18]                 [0.1]
2388440981134693941         [1515966223519279912, 1515966223509088622]                          [2020-11-21, 2020-11-21]                     [1736.09, 370.35]            [0.1, 0.1]
2388440981134693942                              [1515966223526602848]                                      [2020-11-21]                              [138.87]                 [0.1]
2388440981134693943                              [1515966223509089282]                                      [2020-11-21]                              [418.96]                 [0.1]
2388440981134693944  [1515966223509089917, 2273948184839454837, 151...              [2020-11-21, 2020-11-21, 2020-11-21]                 [12.48, 41.64, 53.22]       [0.1, 0.1, 0.1]

[1435266 rows x 4 columns]

In [35]:
import seaborn as sns

length_of_transactions = data["product_id"].apply(len).value_counts()
length_of_transactions.rename_axis("frequency")

# lenth_of_transactions

total = length_of_transactions.sum()

import plotly.express as px
fig = px.bar(length_of_transactions, x=length_of_transactions.index, y=length_of_transactions.values/total)
fig.update_traces(width=0.5)
fig.update_layout(
    xaxis_title="Number of items per transaction",
    yaxis_tickformat =',.0%',
    yaxis_title="Distribution",
    legend_title="Transaction Length Dsitribution",)

fig.show()

c:\ProgramData\Anaconda3\lib\site-packages\seaborn\rcmod.py:82: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if LooseVersion(mpl.__version__) >= "3.0":
c:\ProgramData\Anaconda3\lib\site-packages\setuptools\_distutils\version.py:346: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  other = LooseVersion(other)
c:\ProgramData\Anaconda3\lib\site-packages\xarray\core\pycompat.py:22: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  duck_array_version = LooseVersion(duck_array_module.__version__)
c:\ProgramData\Anaconda3\lib\site-packages\xarray\core\pycompat.py:37: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  duck_array_version = LooseVersion("0.0.0")
c:\ProgramData\Anaconda3\lib\site-packages\xarray\core\pycompat.py:37: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  duck_array_version = LooseVersion("0.0.0")
c:\ProgramData\Anaconda3\lib\site-packages\setuptools\_distutils\version.py:346: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  other = LooseVersion(other)
c:\ProgramData\Anaconda3\lib\site-packages\setuptools\_distutils\version.py:346: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  other = LooseVersion(other)
c:\ProgramData\Anaconda3\lib\site-packages\xarray\core\npcompat.py:82: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if LooseVersion(np.__version__) >= "1.20.0":
c:\ProgramData\Anaconda3\lib\site-packages\setuptools\_distutils\version.py:346: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  other = LooseVersion(other)
c:\ProgramData\Anaconda3\lib\site-packages\xarray\core\pdcompat.py:45: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if LooseVersion(pd.__version__) < "0.25.0":
c:\ProgramData\Anaconda3\lib\site-packages\setuptools\_distutils\version.py:346: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  other = LooseVersion(other)
c:\ProgramData\Anaconda3\lib\site-packages\plotly\io\_renderers.py:395: DeprecationWarning:

distutils Version classes are deprecated. Use packaging.version instead.

c:\ProgramData\Anaconda3\lib\site-packages\plotly\io\_renderers.py:395: DeprecationWarning:

distutils Version classes are deprecated. Use packaging.version instead.

In [36]:
length_of_transactions.sum()

1435266

#### 3.1 Classical Association Rules

In [37]:
import modified_fp_growth_algorithm.modified_fp_growth_latest as mod_fp_growth

rules = mod_fp_growth.fpgrowthFromDataFrame(\
    data,
    minSupRatio=0.005,
    maxSupRatio=1,
    minConf=0,
    item_col=1
    )
    
rules.to_excel("fp_groth_out.xlsx",index=False) 
rules

                                    antecedent sup_antecedent             consequent  sup_consequent                              antecedent&consequent  sup_ant&cons  sup_perc_ant&cons confidence       lift improvement
0                                           []             NA  [1515966223523303302]           44491                              [1515966223523303302]         44491           0.030998         NA         NA          NA
1                                           []             NA  [1515966223523303301]           41076                              [1515966223523303301]         41076           0.028619         NA         NA          NA
2                                           []             NA  [1515966223523303308]           38786                              [1515966223523303308]         38786           0.027024         NA         NA          NA
3                                           []             NA  [1515966223523303310]           38472                              [1515966223523303310]         38472           0.026805         NA         NA          NA
4                                           []             NA  [1515966223523303314]           36530                              [1515966223523303314]         36530           0.025452         NA         NA          NA
5                                           []             NA  [1515966223523303321]           31652                              [1515966223523303321]         31652           0.022053         NA         NA          NA
6                        [1515966223523303310]          38472  [1515966223523303314]           36530         [1515966223523303314, 1515966223523303310]         26080           0.018171   0.677896  26.634561    0.652444
7                        [1515966223523303301]          41076  [1515966223523303321]           31652         [1515966223523303321, 1515966223523303301]         19844           0.013826   0.483104  21.906466    0.461051
8                                           []             NA  [1515966223523303312]           15994                              [1515966223523303312]         15994           0.011144         NA         NA          NA
9                                           []             NA  [1515966223509117074]           14284                              [1515966223509117074]         14284           0.009952         NA         NA          NA
10                       [1515966223523303310]          38472  [1515966223523303312]           15994         [1515966223523303312, 1515966223523303310]         12109           0.008437   0.314748  28.244821    0.303605
11                                          []             NA  [1515966223509106786]           12058                              [1515966223509106786]         12058           0.008401         NA         NA          NA
12                                          []             NA  [1515966223523303300]           10762                              [1515966223523303300]         10762           0.007498         NA         NA          NA
13                       [1515966223523303314]          36530  [1515966223523303312]           15994         [1515966223523303312, 1515966223523303314]         10401           0.007247   0.284725  25.550578    0.273581
14                                          []             NA  [1515966223523303342]            9498                              [1515966223523303342]          9498           0.006618         NA         NA          NA
15                                          []             NA  [2273948186349404174]            9445                              [2273948186349404174]          9445           0.006581         NA         NA          NA
16  [1515966223523303314, 1515966223523303310]          26080  [1515966223523303312]           15994  [1515966223523303314, 1515966223523303312, 151...          9031           0.006292   0.346281  31.074458    0.335137
17                                          []             NA  [2273948316473492113]            8968                              [2273948316473492113]          8968           0.006248         NA         NA          NA
18                                          []             NA  [1515966223509088521]            8867                              [1515966223509088521]          8867           0.006178         NA         NA          NA
19                       [1515966223523303308]          38786  [1515966223523303310]           38472         [1515966223523303308, 1515966223523303310]          8726           0.006080   0.224978   8.393205    0.198173
20                                          []             NA  [2273948218662322995]            8692                              [2273948218662322995]          8692           0.006056         NA         NA          NA
21                                          []             NA  [1515966223523303307]            8577                              [1515966223523303307]          8577           0.005976         NA         NA          NA
22                                          []             NA  [1515966223523303362]            8343                              [1515966223523303362]          8343           0.005813         NA         NA          NA
23                       [1515966223523303301]          41076  [1515966223523303314]           36530         [1515966223523303301, 1515966223523303314]          8304           0.005786   0.202162   7.942952     0.17671
24                       [1515966223523303308]          38786  [1515966223523303314]           36530         [1515966223523303308, 1515966223523303314]          8276           0.005766   0.213376   8.383555    0.187924
25                       [1515966223523303310]          38472  [2273948218662322995]            8692         [2273948218662322995, 1515966223523303310]          8229           0.005733   0.213896  35.319535     0.20784
26                       [1515966223523303301]          41076  [1515966223523303310]           38472         [1515966223523303301, 1515966223523303310]          8219           0.005726   0.200093   7.464805    0.173288
27                                          []             NA  [2273948227654910595]            7963                              [2273948227654910595]          7963           0.005548         NA         NA          NA
28                                          []             NA  [1515966223509089067]            7235                              [1515966223509089067]          7235           0.005041         NA         NA          NA

In [38]:
# A minSupRatio of 0.007 means, in case of profitability, that it represents 0.007 of total revenues rspectively profit. We made the profit fo each product equal.
# Let's oberserve what kind of items we have found.


rules_exploded = rules.explode("antecedent&consequent")[["antecedent&consequent","sup_ant&cons"]]
rules_exploded.insert(0,"rules_index",rules_exploded.index)


rules_labeled = pd.merge(rules_exploded,unique_items, how='inner', left_on = 'antecedent&consequent', right_on = 'product_id').sort_values("rules_index").reset_index(drop=True)


rules_labeled.to_excel("rules_labeled.xlsx",index=False)

rules_labeled

    rules_index antecedent&consequent  sup_ant&cons           product_id             category_id                  category_code    brand   price
0             0   1515966223523303302         44491  1515966223523303302                     nan                          57.87      nan     nan
1             1   1515966223523303301         41076  1515966223523303301                     nan                          16.18      nan     nan
2             2   1515966223523303308         38786  1515966223523303308                     nan                          29.63      nan     nan
3             3   1515966223523303310         38472  1515966223523303310                     nan                           8.10      nan     nan
4             4   1515966223523303314         36530  1515966223523303314                     nan                           9.26      nan     nan
5             5   1515966223523303321         31652  1515966223523303321                     nan                          16.18      nan     nan
6             6   1515966223523303310         26080  1515966223523303310                     nan                           8.10      nan     nan
7             6   1515966223523303314         26080  1515966223523303314                     nan                           9.26      nan     nan
8             7   1515966223523303301         19844  1515966223523303301                     nan                          16.18      nan     nan
9             7   1515966223523303321         19844  1515966223523303321                     nan                          16.18      nan     nan
10            8   1515966223523303312         15994  1515966223523303312                     nan                           6.94      nan     nan
11            9   1515966223509117074         14284  1515966223509117074  2.2681054278729078e+18                            nan  samsung   30.07
12           10   1515966223523303312         12109  1515966223523303312                     nan                           6.94      nan     nan
13           10   1515966223523303310         12109  1515966223523303310                     nan                           8.10      nan     nan
14           11   1515966223509106786         12058  1515966223509106786   2.268105428166509e+18         electronics.smartphone  samsung  138.87
15           12   1515966223523303300         10762  1515966223523303300                     nan                          13.87      nan     nan
16           13   1515966223523303314         10401  1515966223523303314                     nan                           9.26      nan     nan
17           13   1515966223523303312         10401  1515966223523303312                     nan                           6.94      nan     nan
18           14   1515966223523303342          9498  1515966223523303342                     nan                          92.59      nan     nan
19           15   2273948186349404174          9445  2273948186349404174  2.2681054942687404e+18                            nan      neo   30.07
20           16   1515966223523303314          9031  1515966223523303314                     nan                           9.26      nan     nan
21           16   1515966223523303310          9031  1515966223523303310                     nan                           8.10      nan     nan
22           16   1515966223523303312          9031  1515966223523303312                     nan                           6.94      nan     nan
23           17   2273948316473492113          8968  2273948316473492113   2.268105428166509e+18         electronics.smartphone  samsung  162.01
24           18   1515966223509088521          8867  1515966223509088521   2.268105428166509e+18         electronics.smartphone  samsung  115.72
25           19   1515966223523303310          8726  1515966223523303310                     nan                           8.10      nan     nan
26           19   1515966223523303308          8726  1515966223523303308                     nan                          29.63      nan     nan
27           20   2273948218662322995          8692  2273948218662322995   2.268105506180563e+18                            nan    grohe  184.72
28           21   1515966223523303307          8577  1515966223523303307  2.3744989139998725e+18         electronics.smartphone     awax    5.56
29           22   1515966223523303362          8343  1515966223523303362                     nan                          69.44      nan     nan
30           23   1515966223523303314          8304  1515966223523303314                     nan                           9.26      nan     nan
31           23   1515966223523303301          8304  1515966223523303301                     nan                          16.18      nan     nan
32           24   1515966223523303308          8276  1515966223523303308                     nan                          29.63      nan     nan
33           24   1515966223523303314          8276  1515966223523303314                     nan                           9.26      nan     nan
34           25   1515966223523303310          8229  1515966223523303310                     nan                           8.10      nan     nan
35           25   2273948218662322995          8229  2273948218662322995   2.268105506180563e+18                            nan    grohe  184.72
36           26   1515966223523303310          8219  1515966223523303310                     nan                           8.10      nan     nan
37           26   1515966223523303301          8219  1515966223523303301                     nan                          16.18      nan     nan
38           27   2273948227654910595          7963  2273948227654910595   2.268105392070329e+18  appliances.environment.vacuum  samsung  104.14
39           28   1515966223509089067          7235  1515966223509089067   2.268105428166509e+18         electronics.smartphone  samsung  138.87

#### 3.2 Profit based Association Rules (No limitations on transaction length)

In [39]:
import modified_fp_growth_algorithm.modified_fp_growth_latest as mod_fp_growth

#For better trackingI take price instead of profit as profit, because tracking ius easier and at moment I anyway just multiply by 0.1 for profit
# We see how "super efficient it is, only 6.8 seconds for 13k rules inclduing writing to Excel"
rules = mod_fp_growth.fpgrowthFromDataFrame(\
    data,
    minSupRatio=0.0005,
    maxSupRatio=1,
    minConf=0,
    item_col=1,
    profit_col=3,
    max_profit = max_profit,
    profit_sensitivity = lambda x : 1 * x
    )
    
rules.to_excel("fp_groth_out.xlsx",index=False) 
rules

                antecedent sup_antecedent             consequent  sup_consequent                       antecedent&consequent  sup_ant&cons  sup_perc_ant&cons confidence       lift improvement  profit_associated  perc_of_total_profit  profit_associated_prev     net_change  profit_last_item  loss_by_change
0                       []             NA  [1515966223509088567]            4336                       [1515966223509088567]          4336           0.003062         NA         NA          NA       3.712613e+06              0.010944                    0.00       0.000000      3.712613e+06            0.00
1                       []             NA  [1515966223509088671]            2587                       [1515966223509088671]          2587           0.001827         NA         NA          NA       2.394708e+06              0.007059                    0.00       0.000000      2.394708e+06            0.00
2                       []             NA  [1515966223509089284]            1967                       [1515966223509089284]          1967           0.001389         NA         NA          NA       2.390397e+06              0.007046                    0.00       0.000000      2.390397e+06            0.00
3                       []             NA  [1515966223509088532]            6466                       [1515966223509088532]          6466           0.004566         NA         NA          NA       1.946823e+06              0.005739                    0.00       0.000000      1.946823e+06            0.00
4                       []             NA  [1515966223509088628]            2242                       [1515966223509088628]          2242           0.001583         NA         NA          NA       1.921896e+06              0.005665                    0.00       0.000000      1.921896e+06            0.00
..                     ...            ...                    ...             ...                                         ...           ...                ...        ...        ...         ...                ...                   ...                     ...            ...               ...             ...
414                     []             NA  [1515966223509104322]             289                       [1515966223509104322]           289           0.000204         NA         NA          NA       1.705822e+05              0.000503                    0.00       0.000000      1.705822e+05            0.00
415  [1515966223510174551]           5235  [1515966223509088628]            2242  [1515966223509088628, 1515966223510174551]           160           0.000113   0.030564  19.305958     0.02898       1.704854e+05              0.000503              1090502.85 -920017.407716      1.371558e+05     -1057173.25
416                     []             NA  [2298437340659450199]             263                       [2298437340659450199]           263           0.000186         NA         NA          NA       1.704582e+05              0.000502                    0.00       0.000000      1.704582e+05            0.00
417                     []             NA  [1515966223517993700]             283                       [1515966223517993700]           283           0.000200         NA         NA          NA       1.703179e+05              0.000502                    0.00       0.000000      1.703179e+05            0.00
418                     []             NA  [1515966223509255443]             733                       [1515966223509255443]           733           0.000518         NA         NA          NA       1.696602e+05              0.000500                    0.00       0.000000      1.696602e+05            0.00

[419 rows x 16 columns]

In [40]:
# A minSupRatio of 0.007 means, in case of profitability, that it represents 0.007 of total revenues rspectively profit. We made the profit fo each product equal.
# Let's oberserve what kind of items we have found.


rules_exploded = rules.explode("antecedent&consequent")[["antecedent&consequent","sup_ant&cons","profit_associated","perc_of_total_profit"]]
rules_exploded.insert(0,"rules_index",rules_exploded.index)

rules_labeled =pd.merge(rules_exploded,unique_items, how="inner", left_on="antecedent&consequent",right_on="product_id").sort_values("rules_index").reset_index(drop=True)

rules_labeled.to_excel("rules_labeled.xlsx",index=False)

rules_labeled.head(15)

    rules_index antecedent&consequent  sup_ant&cons  profit_associated  perc_of_total_profit           product_id             category_id                           category_code    brand    price
0             0   1515966223509088567          4336         3712613.28              0.010944  1515966223509088567   2.268105428166509e+18                  electronics.smartphone    apple   856.23
1             1   1515966223509088671          2587         2394708.29              0.007059  1515966223509088671   2.268105428166509e+18                  electronics.smartphone    apple   925.67
2             2   1515966223509089284          1967         2390396.75              0.007046  1515966223509089284   2.268105428166509e+18                  electronics.smartphone  samsung  1215.25
3             3   1515966223509088532          6466         1946823.00              0.005739  1515966223509088532   2.268105428166509e+18                  electronics.smartphone  samsung    300.9
4             4   1515966223509088628          2242         1921896.24              0.005665  1515966223509088628   2.268105428166509e+18                  electronics.smartphone  samsung   856.46
5             5   1515966223509130879          4502         1719403.84              0.005068  1515966223509130879  2.2681053899563999e+18               appliances.kitchen.washer  samsung   381.92
6             6   1515966223509106786         12058         1675049.94              0.004938  1515966223509106786   2.268105428166509e+18                  electronics.smartphone  samsung   138.87
7             7   2273948218662322995          8692         1605586.24              0.004733  2273948218662322995   2.268105506180563e+18                                     nan    grohe   184.72
8             8   1515966223509089438          1778         1522376.94              0.004488  1515966223509089438   2.268105428166509e+18                  electronics.smartphone    apple   856.23
9             9   1515966223509088610          2747         1462980.24              0.004312  1515966223509088610   2.268105428166509e+18                  electronics.smartphone  samsung   532.38
10           10   2273948189981671502          1056         1462971.84              0.004312  2273948189981671502  2.2681056302564646e+18                                     nan    cilek  1385.39
11           11   2273948316473492113          8968         1453067.69              0.004283  2273948316473492113   2.268105428166509e+18                  electronics.smartphone  samsung   162.01
12           12   1515966223509089293          5354         1425127.72              0.004201  1515966223509089293  2.3607418670179953e+18  appliances.environment.air_conditioner     beko   266.18
13           13   1515966223509128687          1703         1300870.61              0.003835  1515966223509128687   2.268105393848714e+18        appliances.kitchen.refrigerators  samsung   763.87
14           14   1515966223509089533          1684         1285952.92              0.003791  1515966223509089533   2.268105428166509e+18                  electronics.smartphone    apple   763.63

#### 3.2 Profit based Association Rules (Limitations on transaction length as 2)

In [42]:
import modified_fp_growth_algorithm.modified_fp_growth_latest as mod_fp_growth

#For better trackingI take price instead of profit as profit, because tracking ius easier and at moment I anyway just multiply by 0.1 for profit
# We see how "super efficient it is, only 6.8 seconds for 13k rules inclduing writing to Excel"
rules = mod_fp_growth.fpgrowthFromDataFrame(\
    data,
    minSupRatio=0.0004,
    maxSupRatio=1,
    minTransactionLength=2,
    maxTransactionLength=10,
    minConf=0,
    item_col=1,
    profit_col=3,
    max_profit = max_profit,
    profit_sensitivity = lambda x : 1 * x
    )
    
rules.to_excel("fp_groth_out.xlsx",index=False) 
rules

                                    antecedent  sup_antecedent             consequent  sup_consequent                              antecedent&consequent  sup_ant&cons  sup_perc_ant&cons  confidence        lift  improvement  profit_associated  perc_of_total_profit  profit_associated_prev    net_change  profit_last_item  loss_by_change
0                        [2273948218662322995]            8692  [2273948218662322996]            6132         [2273948218662322995, 2273948218662322996]          3863           0.002728    0.444432  102.642333     0.440102       1.269768e+06              0.003743              1605586.24 -3.358181e+05     556194.740000   -8.920129e+05
1   [2273948218662322995, 2273948218662322996]            3863  [2273948186248741817]            3062  [2273948218662322995, 2273948218662322996, 227...          1007           0.000711    0.260678  120.565554     0.258516       4.288813e+05              0.001264              1269768.10 -8.408868e+05      97880.400000   -9.387672e+05
2                        [2273948218662322995]            8692  [2273948186248741817]            3062         [2273948218662322995, 2273948186248741817]          1386           0.000979    0.159457   73.749995     0.157295       3.907411e+05              0.001152              1605586.24 -1.214845e+06     134719.200000   -1.349564e+06
3                        [2273948297037087396]            7105  [2273948222722409184]            5844         [2273948222722409184, 2273948297037087396]          4158           0.002936    0.585222  141.818819     0.581095       3.543032e+05              0.001044               346866.10  7.437080e+03     151309.620000   -1.438725e+05
4                        [1515966223509117074]           14284  [1515966223509088532]            6466         [1515966223509117074, 1515966223509088532]          1001           0.000707    0.070078   15.348721     0.065513       3.314894e+05              0.000977               429549.95 -9.806054e+04     301387.229044   -3.994478e+05
5                        [2273948297037087396]            7105  [1515966223509088567]            4336         [1515966223509088567, 2273948297037087396]           359           0.000253    0.050528   16.503071     0.047466       3.249129e+05              0.000958               346866.10 -2.195315e+04     307386.570000   -3.293397e+05
6                        [1515966223509117074]           14284  [2273948316473492113]            8968         [1515966223509117074, 2273948316473492113]          1605           0.001133    0.112363   17.744071     0.106031       3.083208e+05              0.000909               429549.95 -1.212292e+05     260055.044876   -3.812842e+05
7                        [2273948222722409184]            5844  [1515966223509088567]            4336         [2273948222722409184, 1515966223509088567]           341           0.000241    0.058350   19.058055     0.055289       3.043834e+05              0.000897               212663.16  9.172026e+04     291974.430000   -2.002542e+05
8                        [2273948218662322996]            6132  [2273948186248741817]            3062         [2273948218662322996, 2273948186248741817]          1208           0.000853    0.196999   91.113614     0.194837       2.913454e+05              0.000859               882885.36 -5.915399e+05     117417.600000   -7.089575e+05
9                        [1515966223509117074]           14284  [1515966223509089514]            4981         [1515966223509089514, 1515966223509117074]           948           0.000669    0.066368   18.869727     0.062851       2.700240e+05              0.000796               429549.95 -1.595259e+05     241515.654591   -4.010416e+05
10  [2273948222722409184, 2273948297037087396]            4158  [1515966223509088567]            4336  [1515966223509088567, 2273948222722409184, 227...           252           0.000178    0.060606   19.794770     0.057544       2.372429e+05              0.000699               354303.18 -1.170603e+05     215769.960000   -3.328303e+05
11                       [2273948304913989705]            1269  [2273948305341808929]            1237         [2273948304913989705, 2273948305341808929]           195           0.000138    0.153664  175.924757     0.152791       2.225262e+05              0.000656               757846.80 -5.353206e+05     106072.200000   -6.413928e+05
12                       [1515966223509117074]           14284  [1515966223509104769]            1947         [1515966223509117074, 1515966223509104769]           800           0.000565    0.056007   40.737827     0.054632       1.905217e+05              0.000562               429549.95 -2.390283e+05     166464.000000   -4.054923e+05
13                       [1515966223510174551]            5235  [1515966223509089284]            1967         [1515966223509089284, 1515966223510174551]           131           0.000093    0.025024   18.016645     0.023635       1.864864e+05              0.000550              1090502.85 -9.040165e+05     159197.750000   -1.063214e+06
14                       [2273948222722409184]            5844  [1515966223509089533]            1684         [2273948222722409184, 1515966223509089533]           231           0.000163    0.039528   33.241710     0.038339       1.848046e+05              0.000545               212663.16 -2.785854e+04     176398.530000   -2.042571e+05
15                       [2273948297037087396]            7105  [1515966223509088610]            2747         [2273948297037087396, 1515966223509088610]           317           0.000224    0.044616   23.001714     0.042677       1.843018e+05              0.000543               346866.10 -1.625643e+05     168825.895916   -3.313902e+05
16                       [1515966223509106786]           12058  [1515966223509089067]            7235         [1515966223509089067, 1515966223509106786]           632           0.000446    0.052413   10.259517     0.047305       1.755851e+05              0.000518              1675049.94 -1.499465e+06      87790.101462   -1.587255e+06
17                       [2273948297037087396]            7105  [1515966223509089284]            1967         [1515966223509089284, 2273948297037087396]           138           0.000097    0.019423   13.984093     0.018034       1.744417e+05              0.000514               346866.10 -1.724244e+05     167704.500000   -3.401289e+05
18                       [1515966223510174551]            5235  [1515966223509088628]            2242         [1515966223509088628, 1515966223510174551]           160           0.000113    0.030564   19.305958     0.028980       1.704854e+05              0.000503              1090502.85 -9.200174e+05     137155.842284   -1.057173e+06
19                       [2273948222722409184]            5844  [1515966223509089284]            1967         [1515966223509089284, 2273948222722409184]           131           0.000093    0.022416   16.139140     0.021027       1.639648e+05              0.000483               212663.16 -4.869832e+04     159197.750000   -2.078961e+05
20                       [1515966223509089284]            1967  [1515966223509088497]             989         [1515966223509089284, 1515966223509088497]            67           0.000047    0.034062   48.775061     0.033364       1.628435e+05              0.000480              2390396.75 -2.227553e+06      81421.750000   -2.308975e+06
21                       [2273948297037087396]            7105  [1515966223509088671]            2587         [1515966223509088671, 2273948297037087396]           167           0.000118    0.023505   12.867069     0.021678       1.627398e+05              0.000480               346866.10 -1.841263e+05     154586.890000   -3.387132e+05
22                       [2273948297037087396]            7105  [1515966223509088628]            2242         [1515966223509088628, 2273948297037087396]           176           0.000124    0.024771   15.647200     0.023188       1.594637e+05              0.000470               346866.10 -1.874024e+05     150871.426512   -3.382738e+05
23                       [2273948189981671503]            1357  [2273948189981671502]            1056         [2273948189981671503, 2273948189981671502]            95           0.000067    0.070007   93.886578     0.069262       1.531609e+05              0.000451               307808.31 -1.546474e+05     131612.050000   -2.862595e+05
24                       [1515966223509088610]            2747  [1515966223509106868]            1359         [1515966223509106868, 1515966223509088610]           230           0.000162    0.083728   87.251598     0.082768       1.464618e+05              0.000432              1462980.24 -1.316518e+06      23969.824871   -1.340488e+06
25                       [2273948222722409184]            5844  [1515966223509088671]            2587         [1515966223509088671, 2273948222722409184]           150           0.000106    0.025667   14.051034     0.023841       1.443090e+05              0.000425               212663.16 -6.835416e+04     138850.500000   -2.072047e+05
26                       [1515966223509117074]           14284  [1515966223509088552]            1789         [1515966223509088552, 1515966223509117074]           633           0.000447    0.044315   35.080615     0.043052       1.433440e+05              0.000423               429549.95 -2.862060e+05     124308.356009   -4.105143e+05
27                       [1515966223509117074]           14284  [1515966223509089261]            2205         [1515966223509117074, 1515966223509089261]           501           0.000354    0.035074   22.526979     0.033517       1.426257e+05              0.000420               429549.95 -2.869242e+05     127559.610000   -4.144838e+05
28  [2273948222722409184, 2273948297037087396]            4158  [1515966223509089284]            1967  [1515966223509089284, 2273948222722409184, 227...           108           0.000076    0.025974   18.700731     0.024585       1.404497e+05              0.000414               354303.18 -2.138535e+05     131247.000000   -3.451005e+05
29                       [2273948222722409184]            5844  [1515966223509088493]            1440         [2273948222722409184, 1515966223509088493]           179           0.000126    0.030630   30.123401     0.029613       1.391027e+05              0.000410               212663.16 -7.356047e+04     132588.880000   -2.061494e+05
30                       [1515966223509117074]           14284  [1515966223509088578]            2632         [1515966223509117074, 1515966223509088578]           415           0.000293    0.029053   15.632774     0.027195       1.374009e+05              0.000405               429549.95 -2.921491e+05     124920.944339   -4.170700e+05
31                       [1515966223509117074]           14284  [2273948218662322995]            8692         [1515966223509117074, 2273948218662322995]           638           0.000451    0.044665    7.277376     0.038528       1.370374e+05              0.000404               429549.95 -2.925126e+05     117851.360000   -4.103639e+05
32                       [2273948297037087396]            7105  [1515966223509089617]            1588         [1515966223509089617, 2273948297037087396]           294           0.000208    0.041379   36.902554     0.040258       1.367776e+05              0.000403               346866.10 -2.100885e+05     122424.540000   -3.325130e+05
33                       [2273948222722409184]            5844  [1515966223509088628]            2242         [1515966223509088628, 2273948222722409184]           153           0.000108    0.026181   16.537478     0.024598       1.367229e+05              0.000403               212663.16 -7.594022e+04     131155.274184   -2.070955e+05
34                       [1515966223509089400]            2956  [1515966223509088610]            2747         [1515966223509089400, 1515966223509088610]           222           0.000157    0.075101   38.718057     0.073162       1.362195e+05              0.000402               239517.00 -1.032975e+05     118231.384521   -2.215289e+05
35                       [2273948297037087396]            7105  [1515966223509089438]            1778         [2273948297037087396, 1515966223509089438]           150           0.000106    0.021112   16.815860     0.019856       1.357575e+05              0.000400               346866.10 -2.111086e+05     128434.500000   -3.395431e+05

In [44]:
# A minSupRatio of 0.007 means, in case of profitability, that it represents 0.007 of total revenues rspectively profit. We made the profit fo each product equal.
# Let's oberserve what kind of items we have found.


rules_exploded = rules.explode("antecedent&consequent")[["antecedent&consequent","sup_ant&cons","profit_associated","perc_of_total_profit"]]
rules_exploded.insert(0,"rules_index",rules_exploded.index)

rules_labeled =pd.merge(rules_exploded,unique_items, how="inner", left_on="antecedent&consequent",right_on="product_id").sort_values("rules_index").reset_index(drop=True)

rules_labeled.to_excel("rules_labeled.xlsx",index=False)

rules_labeled["profit_associated"] = rules_labeled["profit_associated"].astype(int)

rules_labeled.head(15)

    rules_index antecedent&consequent  sup_ant&cons  profit_associated  perc_of_total_profit           product_id             category_id             category_code     brand   price
0             0   2273948218662322995          3863            1269768              0.003743  2273948218662322995   2.268105506180563e+18                       nan     grohe  184.72
1             0   2273948218662322996          3863            1269768              0.003743  2273948218662322996   2.268105506180563e+18                       nan     grohe  143.98
2             1   2273948218662322995          1007             428881              0.001264  2273948218662322995   2.268105506180563e+18                       nan     grohe  184.72
3             1   2273948218662322996          1007             428881              0.001264  2273948218662322996   2.268105506180563e+18                       nan     grohe  143.98
4             1   2273948186248741817          1007             428881              0.001264  2273948186248741817   2.268105535557469e+18                       nan    incase    97.2
5             2   2273948218662322995          1386             390741              0.001152  2273948218662322995   2.268105506180563e+18                       nan     grohe  184.72
6             2   2273948186248741817          1386             390741              0.001152  2273948186248741817   2.268105535557469e+18                       nan    incase    97.2
7             3   2273948297037087396          4158             354303              0.001044  2273948297037087396  2.2681055385689792e+18                       nan  goodride   48.82
8             3   2273948222722409184          4158             354303              0.001044  2273948222722409184  2.2681055429729987e+18  furniture.bedroom.pillow   dogland   36.39
9             4   1515966223509117074          1001             331489              0.000977  1515966223509117074  2.2681054278729078e+18                       nan   samsung   30.07
10            4   1515966223509088532          1001             331489              0.000977  1515966223509088532   2.268105428166509e+18    electronics.smartphone   samsung   300.9
11            5   1515966223509088567           359             324912              0.000958  1515966223509088567   2.268105428166509e+18    electronics.smartphone     apple  856.23
12            5   2273948297037087396           359             324912              0.000958  2273948297037087396  2.2681055385689792e+18                       nan  goodride   48.82
13            6   2273948316473492113          1605             308320              0.000909  2273948316473492113   2.268105428166509e+18    electronics.smartphone   samsung  162.01
14            6   1515966223509117074          1605             308320              0.000909  1515966223509117074  2.2681054278729078e+18                       nan   samsung   30.07

#### 3.3 Sensitivity Analysis

In [ ]:
import math
import datetime

rules = mod_fp_growth.fpgrowthFromDataFrame(\
    df_data_simple_withprofit,
    minSupRatio=0.03,
    maxSupRatio=1,
    minConf=0,
    item_col=1,
    profit_col=2,
    max_profit = 100,
    profit_sensitivity = lambda x : 1 * x
    ) #Only Date

rules

NameError: name 'df_data_simple_withprofit' is not defined